Add Dockerfile
CrayLabs/SmartRedis pull request #150
Opened 2021-09-28 00:50 UTC by gcoelho

Dockerfile for SmartRedis containing

- SmartRedis static library

2021-09-29 20:15 UTC, Spartee requested changes
Thanks for the contribution @gcoelho! I had some minor comments. 

I'm not exactly sure what the best practices are for installing a python library into a docker image that is meant to be included in a build but I listed some out. 

After the Python client is installed I will approve this PR.

Thanks again!

2021-09-29 20:15 UTC, Spartee commented on images/Dockerfile
> +
So ``make lib`` builds the .so for the python library. I'm not sure exactly what the standard practice is for python package images, but I would think we have a couple options

1. manually place the ``smartredis/src/python/module/smartredis` dir in the ``PYTHONPATH``
2. run `pip install .`` (non-editable install)
3. run ``pip install -e .`` (editable install)

I tend to think option 2 would be the best, but option 1 would work across whatever python environments the user ends up creating in a derivative build (i.e. ``conda``)

2021-09-29 20:15 UTC, Spartee commented on images/Dockerfile
> +    make cmake gcc g++ libc6-dev python3 libpython3-dev pip
we should add a `` && rm -rf /var/lib/apt/lists/*`` line here to reduce the image size.

2021-12-10 00:36 UTC, mellis13 commented
Closing this PR because work will continue on this via #180

2021-12-10 00:36 UTC, closed without merging