Update docstrings for API commands
CrayLabs/SmartRedis pull request #207
Opened 2022-02-04 22:46 UTC by billschereriii

Technical, grammatical, and spelling updates for the docstrings.  A second pass, to make sure the docs build correctly, will follow in a second PR

2022-02-09 17:44 UTC, mellis13 requested changes
Great update to the docs!  

The majority of comments are around prefixing behavior.  For these comments, I tried to comment on each instance to make updates easier.

2022-02-09 17:51 UTC, billschereriii commented on include/addressatcommand.h
> +        *          storage for the host string fails.
Yeah, we at least shouldn't say that we'll throw a RuntimeException in this case

2022-02-09 18:56 UTC, billschereriii commented on include/c_client.h
> +*            dataset was created and may be prefixed. See set_data_source()
fixed for put_dataset, put_tensor, set_script[_from_file], set_model[_from_file], set_function (only in Python)

2022-02-09 19:54 UTC, billschereriii commented on include/c_client.h
> +*   \details The dataset key used to locate the dataset to be renamed
Fixed for copy/rename for tensor and dataset

2022-02-09 20:58 UTC, billschereriii commented on include/c_client.h
> +*            may be prefixed. See set_data_source()
Good catch!

2022-02-10 23:06 UTC, mellis13 approved these changes
Great improvement to docs!

I tried to point out spots where we might want to continue to improve our use of "name" vs "key", since that was a recent push.  Some of these may be subjective, so not all of them necessarily need to be changed.

2022-02-10 23:06 UTC, mellis13 commented on include/c_client.h
> +*   \brief Get a model in the database.   The memory associated with the
Extra spaces?

2022-02-10 23:35 UTC, billschereriii commented on src/python/module/smartredis/client.py
> +        The tensor name used to locate the tensor
Agreed

2022-02-11 00:03 UTC, merged