Release notes for SmartRedis v0.3.1
CrayLabs/SmartRedis pull request #263
Opened 2022-06-23 18:18 UTC by billschereriii

Release notes for SmartRedis version 0.3.1 release

2022-06-23 20:01 UTC, mellis13 approved these changes
Thanks for putting this together.  Just a couple of comments.  It's amazing to see how much work has gone into this release!

2022-06-23 20:39 UTC, ashao requested changes
I would recommend that we try to have a shorter set of release notes, though this level of detail might be right for the changelog itself. For release notes, highlighting the primary new functionality (i.e. the new threaded capabilities and the dataset aggregation) would make it more likely that we would have casual (or advanced) users understand the major improvements.

2022-06-23 20:39 UTC, ashao commented on doc/changelog.rst
> + - Implement multithreaded execution of parallel tasks, including all multi-shard operations. The number of threads devoted for this purpose is controlled by the new environment variable SR_THERAD_CO
If we go for a shorter, pithier style of release notes, I'd say reword this to:
"Many of the new operations related to dataset aggregation and multigpu functions can now be parallelized based on a user-specified number of threads"

2022-06-23 20:39 UTC, ashao commented on doc/changelog.rst
> + - Added API calls for all clients to delete models and scripts from the backend database. (PR240_) New commands are:
Probably eliminate the description of the new methods

2022-06-23 20:39 UTC, ashao commented on doc/changelog.rst
> + - Added clustered Redis testing to automated GitHub check-in testing. (PR239_)
Maybe the right way to organize this is by theme by either the portion of the code (e.g. 'Fortran Client') or by type of change (e.g. bug fix, performance enhancements, quality of life).

2022-06-24 16:47 UTC, mellis13 approved these changes

2022-06-24 17:10 UTC, merged