Update linking instructions and test builds
CrayLabs/SmartRedis pull request #277
Opened 2022-08-23 23:28 UTC by ashao

https://github.com/CrayLabs/SmartRedis/pull/245 introduced the ability to compile the Fortran
clients into their own shared libraries that Fortran applications can build against. Here we
include documentation to guide users to incorporate the new library into their own build
systems. This includes specific instructions for the CMake-based build systems as well
as compiler flags at both the preprocessing and link stages. Lastly, the Fortran tests
now link against the Fortran library, slightly decreasing the build time.

2022-08-25 19:07 UTC, billschereriii commented on .github/workflows/run_tests_uds.yml
> +          make test-verbose
I suspect you need to make this change to the post-merge tests yml file as well

2022-08-25 19:08 UTC, billschereriii commented on doc/changelog.rst
> +- A new make target `make lib-with-fortran` now compiles the Fortran client and dataset into its own library which applications can link against (PR245_)
These should be in reverse chronological order to be consistent with earlier changelogs

2022-08-25 19:12 UTC, billschereriii commented on src/fortran/client.F90
> +    write(stderr,*) "SmartRedis Client has not been initialized"
Good catch!

2022-08-25 19:23 UTC, billschereriii approved these changes
Some good updates to clean up the Fortran and bring it to standard. A few minor comments to address, but nothing worth holding up approval over

2022-08-26 20:29 UTC, mellis13 requested changes
Thanks for this PR -- it will be really nice to have fortran users be able to link against a fortran library.

2022-08-27 00:45 UTC, ashao commented on doc/install/from_source.rst
> -Developer Makefile
Yes, it's because of redundant information. I'll submit a SmartSim PR to update.

2022-08-29 06:09 UTC, mellis13 approved these changes
Looks good to merge.  Let's just make an issue to update SmartSim docs because of the deleted file and address that next.

2022-08-31 17:13 UTC, merged