Better error capabilities for Fortran
CrayLabs/SmartRedis pull request #284
Opened 2022-12-01 21:02 UTC by billschereriii

2022-12-01 21:46 UTC, billschereriii commented
PGP token was timing out so I've rerun jobs

2022-12-05 19:48 UTC, ashao requested changes
Looks really good and especially like how compact the code was to pass a C-string to a Fortran string. Biggest suggestions (as we talked about):
- Combine the two methods so that we just concatenate the error and the location
- Add new function called `print_last_error` that writes to a `STDERR` by default or optionally a user-specifed unit

2022-12-05 19:48 UTC, ashao commented on src/fortran/errors.F90
> +  get_last_error = make_str(cstr, cstr_len)
```
TRIM(make_str(cstr1,cstr1_len))//TRIM(make_str(cstr2,cstr2_len))
```

2022-12-05 19:48 UTC, ashao commented on src/fortran/errors.F90
> +!  end block
Old dev code

2022-12-05 19:48 UTC, ashao commented on src/fortran/errors/errors_interfaces.inc
> +!end interface
Old dev code

2022-12-05 19:48 UTC, ashao commented on src/fortran/errors.F90
> +public :: get_last_error, get_last_error_location
See review notes

2022-12-05 21:17 UTC, ashao approved these changes

2022-12-05 21:21 UTC, merged