object-based logging for Python
CrayLabs/SmartRedis pull request #289
Opened 2023-01-05 22:38 UTC by billschereriii

Enable user-initiated logging from {client, dataset, logcontext}.{log_data, log_warning, log_error} methods for Python users

2023-01-06 21:04 UTC, MattToast requested changes
Looks great!! One small concern regarding multiple pointers that look like they should always be pointing to the same object that I wanted bring to attention but otherwise looks fantastic!

2023-01-06 21:20 UTC, billschereriii commented on src/python/module/smartredis/srobject.py
> +        :return: The newly constructor SRObject from the PySRObject
fixed

2023-01-06 23:53 UTC, MattToast approved these changes
LGTM!!

2023-01-07 00:00 UTC, ashao approved these changes
Looks great, had a similar comment to @MattToast, but I like his suggestion better.

2023-01-07 00:00 UTC, merged