Dataset inspection functionality
CrayLabs/SmartRedis pull request #291
Opened 2023-01-19 22:57 UTC by billschereriii

Add dataset inspection capabilities, including:

- Get a list of metadata field names
- Get the type of a metadata field
- Get a list of tensor names
- Get the type of a tensor

Support added for C++, Python, C, and Fortran, though Fortran support the two list functions is deferred to a future PR due to the inherent difficulty in Fortran of working with arrays of C style strings

2023-01-21 00:38 UTC, MattToast reviewed
Did an in depth look at the python/pybind/Py*.cpp and everything looks great!! Peaked through everything else (aside of Fortran) and didn't see anything that would immediately raise any red flags.

Overall LGTM!! Withholding approval simply to allow others time to review.

2023-01-23 00:44 UTC, billschereriii commented on src/c/c_dataset.cpp
> +}
It's preferred, but not mandatory. I'll add one

2023-01-23 17:56 UTC, billschereriii commented on src/c/c_dataset.cpp
> +}
Added

2023-01-23 23:10 UTC, mellis13 requested changes
Great addition to the library!  Just a couple of small comments/questions.

2023-01-23 23:15 UTC, billschereriii commented on include/dataset.h
> +        void set_name(std::string name) { _dsname = name; }
Not sure if it matters but we certainly could

2023-01-23 23:15 UTC, billschereriii commented on include/dataset.h
> +        SRMetaDataType get_metadata_field_type(const std::string& name);
I believe they do. I'll add throws documentation

2023-01-23 23:16 UTC, billschereriii commented on src/cpp/dataset.cpp
> +        *data = NULL;
Probably, will do

2023-01-23 23:18 UTC, billschereriii commented on src/cpp/dataset.cpp
> +    if (_metadata.has_field(".tensor_names")) {
The existence of the `.tensor_names` field implied to me that there was a performance or other concern with interrogating the tensorpack, which is why I used that source. Open to discussion on this point if you feel strongly that the implementation should be changed

2023-01-24 00:21 UTC, billschereriii commented on include/c_dataset.h
> +*   \param ttype Receives the type for the specified metadata field
fixed

2023-01-24 00:24 UTC, billschereriii commented on include/dataset.h
> +        void set_name(std::string name) { _dsname = name; }
Added an exception

2023-01-24 00:36 UTC, billschereriii commented on include/dataset.h
> +        SRMetaDataType get_metadata_field_type(const std::string& name);
Actually, get_tensor_type() would have just crashed.

2023-01-24 00:36 UTC, billschereriii commented on src/cpp/dataset.cpp
> +    if (_metadata.has_field(".tensor_names")) {
Nothing actionable here short of eliminating the duplication, but that's high risk and I'll move that to a different issue for separate resolution

2023-01-24 21:35 UTC, ashao approved these changes
Fortran implementation is good to go! No comments from me

2023-01-24 21:42 UTC, mellis13 approved these changes
LGTM -- thanks!

2023-01-24 21:51 UTC, merged