Template-based decorators for PyBind layer
CrayLabs/SmartRedis pull request #315
Opened 2023-03-16 22:12 UTC by billschereriii

WIP, showing direction

2023-03-16 23:26 UTC, billschereriii commented
Transformation complete

2023-03-17 18:50 UTC, MattToast requested changes
Looks amazing!! So much boilerplate removed! Caught a couple of misnamed `MAKE_CLIENT_API` calls, but overall everything here looks fantastic!

2023-03-17 18:50 UTC, MattToast commented on src/python/src/pyclient.cpp
> +    MAKE_CLIENT_API("copy_dataset", {
per convo, we might be able to do something with `__func__`

2023-03-17 19:13 UTC, billschereriii commented on src/python/src/pyclient.cpp
> +    MAKE_CLIENT_API("copy_dataset", {
done and done

2023-03-17 19:13 UTC, billschereriii commented on src/python/src/pyclient.cpp
> +    MAKE_CLIENT_API("run_script", {
moot with use of __func__

2023-03-17 19:25 UTC, MattToast approved these changes
This looks amazing!! Thanks for all the hard work on this, this removes soooo much repetitive boilerplate!! LGTM pending tests!!

2023-03-17 19:34 UTC, merged